service: mine
runtime: go115

handlers:
- url: /.*
  script: auto

env_variables:
  APPENGINE_CONFIRM: "true"
  APPENGINE_CONFIG: "gs://k8s-testgrid-hackathon/config"
  APPENGINE_GROUP: "michelle192837"
