# from kubernetes/test-infra:
# go build k8s.io/test-infra/testgrid/cmd/configurator
# mv ./configurator ~/bin/configurator
# ~/bin/configurator --yaml hackathon/config.yaml --print-text --oneshot --output gs://k8s-testgrid-hackathon/config
#
# Issues:
# * Crashes when not using prow
# * Deadlocks when ctrl-c
# * No line numbers on error messages
# * Apparently needs a default.yaml
# * really wants prow junk

test_groups:
- name: chaodaiG
  gcs_prefix: k8s-testgrid-hackathon/data/chaodaiG
- name: chases2
  gcs_prefix: k8s-testgrid-hackathon/data/chases2
  column_header:
  - configuration_value: "Game Message"
- name: cjwagner
  gcs_prefix: k8s-testgrid-hackathon/data/cjwagner
  column_header:
  - configuration_value: "Game Message"
- name: e-blackwelder
  gcs_prefix: k8s-testgrid-hackathon/data/e-blackwelder
- name: fejta
  gcs_prefix: k8s-testgrid-hackathon/data/fejta
- name: michelle192837
  gcs_prefix: k8s-testgrid-hackathon/data/michelle192837
- name: mpherman2
  gcs_prefix: k8s-testgrid-hackathon/data/mpherman2


dashboards:
- name: everyone
  dashboard_tab:
  - name: chaodaiG
    base_options: width=20&show-stale-tests=
    description: chaodaiG
    test_group_name: chaodaiG
  - name: chases2
    base_options: width=20&show-stale-tests=
    description: chases2
    test_group_name: chases2
    open_test_template: # The URL template to visit after clicking on a cell
      url: http://localhost:8080/toe/move
      options:
      - key: g
        value: <environment>
      - key: r
        value: <test-name>
      - key: c
        value: <changelist>
      - key: id
        value: <test-id>
  - name: cjwagner
    base_options: width=20&show-stale-tests=
    description: cjwagner
    test_group_name: cjwagner
    open_test_template: # The URL template to visit after clicking on a cell
      url: http://localhost:8080/toe/move
      options:
        - key: g
          value: <environment>
        - key: r
          value: <test-name>
        - key: c
          value: <changelist>
        - key: id
          value: <test-id>
  - name: e-blackwelder
    base_options: width=20&show-stale-tests=
    description: e-blackwelder
    open_test_template: # The URL template to visit after clicking on a cell
      url: http://localhost:8080/toe/move
      options:
        - key: g
          value: <environment>
        - key: r
          value: <test-name>
        - key: c
          value: <changelist>
        - key: id
          value: <test-id>
    test_group_name: e-blackwelder
  - name: fejta
    base_options: width=20&show-stale-tests=
    description: fejta
    test_group_name: fejta
  - name: mpherman2
    base_options: width=20&show-stale-tests=
    description: mpherman2
    test_group_name: mpherman2
    open_test_template: # The URL template to visit after clicking on a cell
      url: http://k8s-testgrid.appspot.com/pants/col-<changelist>/row-<display-name>/cell-<test-id>
  - name: michelle192837
    base_options: width=20&show-stale-tests=
    description: michelle192837
    test_group_name: michelle192837
    open_test_template: # The URL template to visit after clicking on a cell
      url: http://mine-dot-k8s-testgrid.appspot.com/minesweeper/<test-id>

default_test_group:
  days_of_results: 15 # Number of days of test results to gather and serve.
  tests_name_policy: 2 # replace the name of the test
  num_columns_recent: 10
  use_kubernetes_client: true # These two fields are deprecated and should always be true
  is_external: true
  alert_stale_results_hours: 0 # Don't alert for staleness by default.
  num_failures_to_alert: 0 # Disable red rows.
  code_search_path: github.com/chaodaiG/testgrid/search # URL for regression search links.

default_dashboard_tab:
  open_test_template: # The URL template to visit after clicking on a cell
    url: https://oss-prow.k8s.io/view/gs/<gcs_prefix>/<changelist>
  file_bug_template: # The URL template to visit when filing a bug
    url: # empty
  attach_bug_template: # The URL template to visit when attaching to an existing bug
    url: # empty
    options: #empty
  open_bug_template: # The URL template to visit when visiting an associated bug
    url: https://github.com/chaodaiG/testgrid/issues/
  results_text: Hello world # Text to show in the about menu as a link to another view of the results
  results_url_template: # The URL template to visit after clicking
    url: https://google.come
  code_search_path: github.com/chaodaiG/testgrid/search # URL for regression search links.
  num_columns_recent: 10
  code_search_url_template: # The URL template to visit when searching for changelists
    url: # empty
